### PR TITLE
Add gpg_send() to upload key to key server(s)

### PR DESCRIPTION
**Pull request by datawookie**
As discussed in #10.

Hi @jeroen, I've added some functionality to upload keys. I've tested it locally with my keys and it seems to work. Would appreciate it if you could test on your keys too. I also took the liberty of factoring out the list of key servers into a package global variable, `KEYSERVER`, which can be used by `gpg_recv()` and `gpg_send()`. Best regards, Andrew.

### CODE REVIEW

**Comment by jeroen** [comment]
Thanks! Can you try to use `curl` instead of `httr`? That saves a few dependencies. See the [vignette](https://cran.r-project.org/web/packages/curl/vignettes/intro.html#Using_pipes) for some examples how to post.

Can you use `curl::curl_escape` instead of utils:: URLencode please?

What should happen when the upload fails to upload to any server?

**Comment by datawookie** [comment]
Hi @jeroen, I've made those changes and updated the PR. Please let me know if there's anything else. Thanks, Andrew.

**Comment by jeroen** [comment]
I have rewritten the code a bit to do what I think is the intended gpg API usage. Can you try if this works for you?

**Comment by datawookie** [comment]
Works perfectly, @jeroen. Thanks for allowing me to contribute to this project!

**Comment by jeroen** [comment]
This is on cran now.

**Comment by datawookie** [comment]
Awesome! Thanks for letting me know. The version of {emayili} which uses this feature is also on CRAN now! :)

**Pull request merged**
