### PR TITLE
proofreading , github links

### PR DESCRIPTION
**Pull request by jennybc**

### CODE REVIEW

**Comment by jeroen** [comment]
Thanks! Hopefully you got something out of it :) Did the story as a whole make sense?

**Comment by jennybc** [comment]
I definitely got something out of it. But ended thinking you could write more about "signatures". It's not really clear from the vignette what that means. Could you either address that explicitly or link to something?

**Comment by jeroen** [comment]
Hmm interesting I was thinking that this would be obvious from the [examples](https://cran.r-project.org/web/packages/gpg/vignettes/intro.html#digital_signatures) in the vignette. I guess I should elaborate a bit on the concept of a digital signature.

**Comment by jennybc** [comment]
I do understand more upon a second reading FWIW.

**Pull request merged**
